service: challenge1
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action: "dynamodb:*"
      Resource: "*"
  environment:
    DYNAMODB_CARDS_TABLE_NAME: challenge1 #table name

functions:
  createLoyaltyCard:
    handler: handler.create_loyalty_card
    events:
      - http:
          path: /challenge1
          method: post
  getAllLoyaltyCards:
    handler: handler.get_all_loyalty_card
    events:
      - http:
          path: /challenge1
          method: get
  getOneLoyaltyCard:
    handler: handler.get_one_loyalty_card
    events:
      - http:
          path: /challenge1
          method: get
  

#decrease size of deployment package
package:
  exclude:
    - venv/**
    - node_modules/**

#cloud formation code for deploying dynamodb
resources:
  Resources:
    LoyaltyCardDynamodbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: card_number #primary key
            AttributeType: S
          - AttributeName: email #gsi
            AttributeType: S
        KeySchema:
          - AttributeName: card_number
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_CARDS_TABLE_NAME}
        GlobalSecondaryIndexes:
            - IndexName: emailIndex
              KeySchema:
                - AttributeName: email
                  KeyType: HASH
              Projection:
                ProjectionType: ALL